# Generated by Django 2.2.6 on 2019-10-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicCPF',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicCRM',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='message',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patientCPF',
        ),
        migrations.AddField(
            model_name='prescription',
            name='address',
            field=models.CharField(default='error', max_length=40),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Prescriptions.Medic'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Prescriptions.Patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(default='error', max_length=50),
        ),
    ]
